AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  go-example-extension-sam-layer
  
  Sample SAM Template for go-example-extension-sam-layer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  GoExampleExtensionLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      LayerName: go-example-extension
      Description: Go Example Lambda Extension Layer
      ContentUri: go-example-extension/
      CompatibleRuntimes:
      - nodejs12.x
      - python3.10
      - java11
      - dotnetcore3.1
      - provided.al2
      LicenseInfo: MIT-0
      RetentionPolicy: Retain

  RustExampleExtensionLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      LayerName: rust-example-lambda-runtime-api-proxy-extension
      Description: Rust Example Lambda Extension Layer
      ContentUri: rust-example-lambda-runtime-api-proxy-extension/
      CompatibleRuntimes:
      - nodejs12.x
      - python3.10
      - java11
      - dotnetcore3.1
      - provided.al2
      LicenseInfo: MIT-0
      RetentionPolicy: Retain

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: hello.handler
      Layers:
      - !Ref GoExampleExtensionLayer
      Runtime: provided.al2
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
  HelloWorldFunctionPython:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world-python/
      Handler: hello.handler
      Layers:
      - !Ref RustExampleExtensionLayer
      #- !Ref GoExampleExtensionLayer
      Runtime: python3.10
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/wrapper

Outputs:
  GoExampleExtensionLayer:
    Description: Go Example Lambda Extension Layer Version ARN
    Value: !Ref GoExampleExtensionLayer
  HelloWorldFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
